#!/usr/bin/expect -f

set timeout 60

spawn ssh -o PreferredAuthentications=password -o PubkeyAuthentication=no root@31.97.28.231

expect "password:"
send "62uDLW4RJ9ae28EPVfp5yzT##\r"

expect "root@"

send "cd /root/eon\r"
expect "root@"

send "tail -20 server_final.log\r"
expect "root@"

send "ps aux | grep node\r"
expect "root@"

puts ""
puts "Verificando se o servidor está realmente rodando..."

send "exit\r"
expect eof