#!/usr/bin/expect -f

spawn ssh root@31.97.28.231
expect "password:"
send "62uDLW4RJ9ae28EPVfp5yzT##\r"

expect "root@"
send "cd /root/eon-pro-trading-bot\r"

expect "root@"
send "git pull origin main\r"

expect "root@"
send "cd client\r"

expect "root@"
send "npm run build\r"

expect "root@"
send "cd ..\r"

expect "root@"
send "pm2 restart all\r"

expect "root@"
send "pm2 status\r"

expect "root@"
send "exit\r"
expect eof