#!/usr/bin/expect -f

set timeout 15

spawn ssh -o StrictHostKeyChecking=no -o PreferredAuthentications=password -o PubkeyAuthentication=no root@31.97.28.231
expect "password:"
send "62uDLW4RJ9ae28EPVfp5yzT##\r"
expect "#"

send "cp /tmp/main_debug.js /var/www/html/static/js/main.9ee6e54e.js && echo 'FILE REPLACED' && ls -la /var/www/html/static/js/main*.js\\r"
expect "#"

send "exit\\r"
expect eof