import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'pt' | 'en' | 'es';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  pt: {
    // Navigation and Layout
    'nav.dashboard': 'Dashboard',
    'nav.bots': 'Bots',
    'nav.operations': 'Operações',
    'nav.bankManagement': 'Gestão de Banca',
    'nav.courses': 'Cursos',
    'nav.connect': 'Conectar Corretora',
    'nav.users': 'Usuários',
    'nav.theme': 'Tema',
    'nav.deriv': 'Config. Deriv',
    'nav.broker': 'Corretora',
    'nav.profile': 'Perfil',
    'nav.settings': 'Configurações',
    'nav.logout': 'Sair',
    
    // Common
    'common.save': 'Salvar',
    'common.cancel': 'Cancelar',
    'common.edit': 'Editar',
    'common.delete': 'Excluir',
    'common.loading': 'Carregando...',
    'common.name': 'Nome',
    'common.email': 'Email',
    'common.password': 'Senha',
    'common.confirmPassword': 'Confirmar Senha',
    'common.currentPassword': 'Senha Atual',
    'common.newPassword': 'Nova Senha',
    
    // Dashboard
    'dashboard.welcome': 'Bem-vindo',
    'dashboard.platform': 'Plataforma de Trading Inteligente Premium',
    'dashboard.connectBroker': 'Para começar a operar, você precisa conectar sua conta na Corretora.',
    'dashboard.alreadyAccount': 'Já tem uma conta? Conecte-se. Ainda não tem? Crie uma nova conta gratuita.',
    'dashboard.connectAccount': 'Conectar Conta na Corretora',
    'dashboard.createAccount': 'Criar Conta na Corretora',
    'dashboard.brokerAccount': 'Conta na Corretora',
    'dashboard.connected': 'Conectado',
    'dashboard.notConnected': 'Conta não conectada',
    'dashboard.connect': 'Conectar',
    'dashboard.operationStatus': 'Status da Operação',
    'dashboard.operating': 'Operando',
    'dashboard.stopped': 'Parado',
    'dashboard.startOperation': 'Iniciar Operação',
    'dashboard.quickAccess': 'Acesso Rápido',
    'dashboard.botOperations': 'Operações com Bots',
    'dashboard.tradingCourses': 'Cursos de Trading',
    'dashboard.myProfile': 'Meu Perfil',
    'dashboard.riskWarning': 'Aviso de Risco: O trading envolve riscos significativos. Você pode perder parte ou todo o seu capital investido. Nunca invista mais do que pode perder.',
    
    // Operations
    'operations.title': 'Painel de Operações Premium',
    'operations.connectNeeded': 'Para começar a operar, você precisa conectar sua conta na Corretora.',
    'operations.connectAccount': 'Conectar Conta na Corretora',
    'operations.selectBot': 'Selecionar Bot',
    'operations.startOperation': 'Iniciar Operação',
    'operations.stopOperation': 'Parar Operação',
    'operations.operating': 'Operando...',
    'operations.configuration': 'Configuração',
    'operations.entryAmount': 'Valor de Entrada',
    'operations.martingale': 'Martingale',
    'operations.maxHands': 'Máximo de Mãos',
    'operations.maxRed': 'Máximo de Red',
    'operations.stopLoss': 'Stop Loss',
    'operations.takeProfit': 'Take Profit',
    'operations.save': 'Salvar Configuração',
    'operations.cancel': 'Cancelar',
    'operations.availableBots': 'Bots Disponíveis',
    'operations.noBots': 'Nenhum bot disponível',
    'operations.available': 'Disponível',
    'operations.createdOn': 'Criado em',
    'operations.operationStatus': 'Status da Operação',
    'operations.connectToStart': 'Conecte sua conta na Corretora para começar',
    'operations.connectBroker': 'Conectar na Corretora',
    'operations.selectBotToStart': 'Selecione um bot para começar',
    'operations.chooseBotFromList': 'Escolha um bot da lista ao lado',
    'operations.status': 'Status:',
    'operations.operationRunning': 'Operando',
    'operations.operationStopped': 'Parado',
    'operations.operationLog': 'Log de Operações',
    'operations.configureBot': 'Configurar {botName}',
    'operations.entryValue': 'Valor de Entrada ($)',
    'operations.martingaleValue': 'Valor do Martingale',
    'operations.maxHandsOptional': 'Máximo de Mãos (opcional)',
    'operations.maxRedOptional': 'Red Máximo (opcional)',
    'operations.stopLossOptional': 'Stop Loss (opcional)',
    'operations.takeProfitOptional': 'Take Profit (opcional)',
    
    // Bank Management
    'bank.title': 'Gestão de Banca',
    'bank.refresh': 'Atualizar',
    'bank.configure': 'Configurar',
    'bank.initialCapital': 'Capital Inicial',
    'bank.positiveDays': 'Dias Positivos',
    'bank.negativeDays': 'Dias Negativos',
    'bank.hitRate': 'Taxa de Acerto',
    'bank.currentConfig': 'Configuração Atual',
    'bank.target': 'Meta',
    'bank.stopLoss': 'Stop Loss',
    'bank.capital': 'Capital',
    'bank.growthProjection': 'Projeção de Crescimento (Mensal - 30 dias)',
    'bank.day': 'Dia',
    'bank.stopWin': 'Stop Win',
    'bank.deposit': 'Depósito',
    'bank.finalBalance': 'Saldo Final',
    'bank.result': 'Resultado',
    'bank.accumulated': 'Acumulado',
    'bank.operationRecords': 'Registros de Operações',
    'bank.newRecord': 'Novo Registro',
    'bank.noRecordsFound': 'Nenhum registro encontrado',
    'bank.startAddingResults': 'Comece adicionando seu primeiro resultado de operação para acompanhar seu progresso',
    'bank.date': 'Data',
    'bank.status': 'Status',
    'bank.actions': 'Ações',
    'bank.edit': 'Editar',
    'bank.configTitle': 'Configuração de Gestão de Banca',
    'bank.initialDeposit': 'Depósito Inicial ($)',
    'bank.initialBankValue': 'Valor inicial da sua banca',
    'bank.dailyTarget': 'Meta Diária (%)',
    'bank.desiredDailyGain': 'Percentual de ganho diário desejado',
    'bank.maxDailyLoss': 'Percentual máximo de perda diária',
    'bank.editRecord': 'Editar Registro',
    'bank.newOperationRecord': 'Novo Registro de Operação',
    'bank.operationDate': 'Data da Operação',
    'bank.positiveForGain': 'Valor positivo para ganho, negativo para perda',
    'bank.objectiveAchieved': 'Objetivo Alcançado',
    'bank.pending': 'Pendente',
    'bank.targetReached': 'Meta Atingida',
    'bank.observations': 'Observações',
    'bank.addObservations': 'Adicione suas observações sobre a operação...',
    'bank.update': 'Atualizar',
    'bank.configSavedSuccess': 'Configuração salva com sucesso!',
    'bank.fillRequiredFields': 'Preencha os campos obrigatórios',
    'bank.recordUpdatedSuccess': 'Registro atualizado com sucesso!',
    'bank.recordAddedSuccess': 'Registro adicionado com sucesso!',
    
    // Deriv Connection
    'deriv.title': 'Integração Corretora',
    'deriv.subtitle': 'Conecte sua conta na Corretora para começar a usar os bots de trading automatizados',
    'deriv.connectionStatus': 'Status da Conexão',
    'deriv.connected': 'Conectado',
    'deriv.notConnected': 'Não conectado',
    'deriv.accountConnectedSuccess': 'Conta conectada com sucesso!',
    'deriv.account': 'Conta',
    'deriv.connectFirst': 'Para usar os bots de trading, conecte sua conta na Corretora primeiro.',
    'deriv.disconnecting': 'Desconectando...',
    'deriv.disconnectFromBroker': 'Desconectar da Corretora',
    'deriv.connecting': 'Conectando...',
    'deriv.connectWithBroker': 'Conectar com a Corretora',
    'deriv.noAccountYet': 'Ainda não tem conta? Criar conta na Corretora',
    'deriv.whyConnect': 'Por que conectar?',
    'deriv.automatedTrading': 'Trading Automatizado',
    'deriv.automatedTradingDesc': 'Execute estratégias 24/7 sem intervenção manual',
    'deriv.secureConnection': 'Conexão Segura',
    'deriv.secureConnectionDesc': 'OAuth2 oficial da Corretora, seus dados estão protegidos',
    'deriv.multipleAccounts': 'Múltiplas Contas',
    'deriv.multipleAccountsDesc': 'Gerencie contas demo e real simultaneamente',
    'deriv.securityPrivacy': 'Segurança e Privacidade',
    'deriv.securityPoints': '✓ A conexão utiliza OAuth2 oficial da Corretora\n✓ Seus dados de login nunca são armazenados em nossos servidores\n✓ Você pode revogar o acesso a qualquer momento\n✓ Todas as comunicações são criptografadas (HTTPS/WSS)',
    'deriv.popupBlocked': 'Popup bloqueado. Permita popups para conectar com a Corretora.',
    'deriv.connectionSuccess': 'Conta na Corretora conectada com sucesso!',
    'deriv.connectionError': 'Erro ao conectar com a Corretora',
    'deriv.startConnectionError': 'Erro ao iniciar conexão com a Corretora',
    'deriv.disconnectionSuccess': 'Conta na Corretora desconectada com sucesso!',
    'deriv.disconnectionError': 'Erro ao desconectar da Corretora',
    'deriv.afterSignup': 'Após criar sua conta, volte aqui para conectar!',
    
    // Courses
    'courses.title': 'Academia de Trading Premium',
    'courses.loadingCourses': 'Carregando cursos...',
    'courses.previous': 'Anterior',
    'courses.completed': 'Concluída',
    'courses.markCompleted': 'Marcar Concluída',
    'courses.next': 'Próxima',
    'courses.classesCount': '{current} de {total} aulas',
    'courses.selectClass': 'Selecione uma Aula',
    'courses.selectClassDescription': 'Escolha uma aula da biblioteca {location} para começar sua jornada de aprendizado',
    'courses.locationBelow': 'abaixo',
    'courses.locationBeside': 'ao lado',
    'courses.courseLibrary': 'Biblioteca de Cursos',
    'courses.noCoursesAvailable': 'Nenhum curso disponível',
    'courses.classCompleted': 'Aula marcada como concluída!',
    'courses.errorLoadingCourses': 'Erro ao carregar cursos',
    
    // Profile
    'profile.title': 'Meu Perfil',
    'profile.personalInfo': 'Informações Pessoais',
    'profile.changePassword': 'Alterar Senha',
    'profile.fullName': 'Nome Completo',
    'profile.emailCannotChange': 'O email não pode ser alterado',
    'profile.saveChanges': 'Salvar Alterações',
    'profile.saving': 'Salvando...',
    'profile.changing': 'Alterando...',
    'profile.changePasswordButton': 'Alterar Senha',
    'profile.memberSince': 'Membro desde',
    'profile.administrator': 'Administrador',
    'profile.client': 'Cliente',
    'profile.user': 'Usuário',
    'profile.minCharacters': 'Mínimo 6 caracteres',
    
    // Settings
    'settings.title': 'Configurações',
    'settings.language': 'Idioma',
    'settings.selectLanguage': 'Selecionar Idioma',
    'settings.accountInfo': 'Informações da Conta',
    'settings.user': 'Usuário',
    'settings.type': 'Tipo',
    
    // Languages
    'language.portuguese': 'Português (Brasil)',
    'language.english': 'English (US)',
    'language.spanish': 'Español',
    
    // Messages
    'message.profileUpdated': 'Perfil atualizado com sucesso!',
    'message.passwordChanged': 'Senha alterada com sucesso!',
    'message.languageChanged': 'Idioma alterado com sucesso!',
    'message.loginSuccess': 'Login realizado com sucesso!',
    'message.logoutSuccess': 'Logout realizado com sucesso!',
    'message.accountCreated': 'Conta criada com sucesso! Você pode fazer login agora.',
    
    // Errors
    'error.nameRequired': 'Nome é obrigatório',
    'error.emailRequired': 'Email é obrigatório',
    'error.passwordRequired': 'Senha é obrigatória',
    'error.currentPasswordRequired': 'Senha atual é obrigatória',
    'error.newPasswordRequired': 'Nova senha é obrigatória',
    'error.passwordsNotMatch': 'As senhas não coincidem',
    'error.minPassword': 'Senha deve ter pelo menos 6 caracteres',
    'error.invalidEmail': 'Por favor, insira um email válido',
    'error.emailInUse': 'Email já está em uso',
    'error.invalidCredentials': 'Credenciais inválidas',
  },
  
  en: {
    // Navigation and Layout
    'nav.dashboard': 'Dashboard',
    'nav.bots': 'Bots',
    'nav.operations': 'Operations',
    'nav.bankManagement': 'Bank Management',
    'nav.courses': 'Courses',
    'nav.connect': 'Connect Broker',
    'nav.users': 'Users',
    'nav.theme': 'Theme',
    'nav.deriv': 'Deriv Config',
    'nav.broker': 'Broker',
    'nav.profile': 'Profile',
    'nav.settings': 'Settings',
    'nav.logout': 'Logout',
    
    // Common
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.loading': 'Loading...',
    'common.name': 'Name',
    'common.email': 'Email',
    'common.password': 'Password',
    'common.confirmPassword': 'Confirm Password',
    'common.currentPassword': 'Current Password',
    'common.newPassword': 'New Password',
    
    // Dashboard
    'dashboard.welcome': 'Welcome',
    'dashboard.platform': 'Premium Intelligent Trading Platform',
    'dashboard.connectBroker': 'To start trading, you need to connect your Broker account.',
    'dashboard.alreadyAccount': 'Already have an account? Connect. Don\'t have one? Create a new free account.',
    'dashboard.connectAccount': 'Connect Broker Account',
    'dashboard.createAccount': 'Create Broker Account',
    'dashboard.brokerAccount': 'Broker Account',
    'dashboard.connected': 'Connected',
    'dashboard.notConnected': 'Account not connected',
    'dashboard.connect': 'Connect',
    'dashboard.operationStatus': 'Operation Status',
    'dashboard.operating': 'Operating',
    'dashboard.stopped': 'Stopped',
    'dashboard.startOperation': 'Start Operation',
    'dashboard.quickAccess': 'Quick Access',
    'dashboard.botOperations': 'Bot Operations',
    'dashboard.tradingCourses': 'Trading Courses',
    'dashboard.myProfile': 'My Profile',
    'dashboard.riskWarning': 'Risk Warning: Trading involves significant risks. You may lose part or all of your invested capital. Never invest more than you can afford to lose.',
    
    // Operations
    'operations.title': 'Premium Operations Panel',
    'operations.connectNeeded': 'To start trading, you need to connect your Broker account.',
    'operations.connectAccount': 'Connect Broker Account',
    'operations.selectBot': 'Select Bot',
    'operations.startOperation': 'Start Operation',
    'operations.stopOperation': 'Stop Operation',
    'operations.operating': 'Operating...',
    'operations.configuration': 'Configuration',
    'operations.entryAmount': 'Entry Amount',
    'operations.martingale': 'Martingale',
    'operations.maxHands': 'Max Hands',
    'operations.maxRed': 'Max Red',
    'operations.stopLoss': 'Stop Loss',
    'operations.takeProfit': 'Take Profit',
    'operations.save': 'Save Configuration',
    'operations.cancel': 'Cancel',
    'operations.availableBots': 'Available Bots',
    'operations.noBots': 'No bots available',
    'operations.available': 'Available',
    'operations.createdOn': 'Created on',
    'operations.operationStatus': 'Operation Status',
    'operations.connectToStart': 'Connect your Broker account to start',
    'operations.connectBroker': 'Connect to Broker',
    'operations.selectBotToStart': 'Select a bot to start',
    'operations.chooseBotFromList': 'Choose a bot from the list on the side',
    'operations.status': 'Status:',
    'operations.operationRunning': 'Operating',
    'operations.operationStopped': 'Stopped',
    'operations.operationLog': 'Operation Log',
    'operations.configureBot': 'Configure {botName}',
    'operations.entryValue': 'Entry Value ($)',
    'operations.martingaleValue': 'Martingale Value',
    'operations.maxHandsOptional': 'Max Hands (optional)',
    'operations.maxRedOptional': 'Max Red (optional)',
    'operations.stopLossOptional': 'Stop Loss (optional)',
    'operations.takeProfitOptional': 'Take Profit (optional)',
    
    // Bank Management
    'bank.title': 'Bank Management',
    'bank.refresh': 'Refresh',
    'bank.configure': 'Configure',
    'bank.initialCapital': 'Initial Capital',
    'bank.positiveDays': 'Positive Days',
    'bank.negativeDays': 'Negative Days',
    'bank.hitRate': 'Hit Rate',
    'bank.currentConfig': 'Current Configuration',
    'bank.target': 'Target',
    'bank.stopLoss': 'Stop Loss',
    'bank.capital': 'Capital',
    'bank.growthProjection': 'Growth Projection (Monthly - 30 days)',
    'bank.day': 'Day',
    'bank.stopWin': 'Stop Win',
    'bank.deposit': 'Deposit',
    'bank.finalBalance': 'Final Balance',
    'bank.result': 'Result',
    'bank.accumulated': 'Accumulated',
    'bank.operationRecords': 'Operation Records',
    'bank.newRecord': 'New Record',
    'bank.noRecordsFound': 'No records found',
    'bank.startAddingResults': 'Start by adding your first operation result to track your progress',
    'bank.date': 'Date',
    'bank.status': 'Status',
    'bank.actions': 'Actions',
    'bank.edit': 'Edit',
    'bank.configTitle': 'Bank Management Configuration',
    'bank.initialDeposit': 'Initial Deposit ($)',
    'bank.initialBankValue': 'Your initial bank value',
    'bank.dailyTarget': 'Daily Target (%)',
    'bank.desiredDailyGain': 'Desired daily gain percentage',
    'bank.maxDailyLoss': 'Maximum daily loss percentage',
    'bank.editRecord': 'Edit Record',
    'bank.newOperationRecord': 'New Operation Record',
    'bank.operationDate': 'Operation Date',
    'bank.positiveForGain': 'Positive value for gain, negative for loss',
    'bank.objectiveAchieved': 'Objective Achieved',
    'bank.pending': 'Pending',
    'bank.targetReached': 'Target Reached',
    'bank.observations': 'Observations',
    'bank.addObservations': 'Add your observations about the operation...',
    'bank.update': 'Update',
    'bank.configSavedSuccess': 'Configuration saved successfully!',
    'bank.fillRequiredFields': 'Fill in the required fields',
    'bank.recordUpdatedSuccess': 'Record updated successfully!',
    'bank.recordAddedSuccess': 'Record added successfully!',
    
    // Deriv Connection
    'deriv.title': 'Broker Integration',
    'deriv.subtitle': 'Connect your Broker account to start using automated trading bots',
    'deriv.connectionStatus': 'Connection Status',
    'deriv.connected': 'Connected',
    'deriv.notConnected': 'Not connected',
    'deriv.accountConnectedSuccess': 'Account connected successfully!',
    'deriv.account': 'Account',
    'deriv.connectFirst': 'To use trading bots, connect your Broker account first.',
    'deriv.disconnecting': 'Disconnecting...',
    'deriv.disconnectFromBroker': 'Disconnect from Broker',
    'deriv.connecting': 'Connecting...',
    'deriv.connectWithBroker': 'Connect with Broker',
    'deriv.noAccountYet': 'Don\'t have an account yet? Create Broker Account',
    'deriv.whyConnect': 'Why connect?',
    'deriv.automatedTrading': 'Automated Trading',
    'deriv.automatedTradingDesc': 'Execute strategies 24/7 without manual intervention',
    'deriv.secureConnection': 'Secure Connection',
    'deriv.secureConnectionDesc': 'Official Broker OAuth2, your data is protected',
    'deriv.multipleAccounts': 'Multiple Accounts',
    'deriv.multipleAccountsDesc': 'Manage demo and real accounts simultaneously',
    'deriv.securityPrivacy': 'Security and Privacy',
    'deriv.securityPoints': '✓ Connection uses official Broker OAuth2\n✓ Your login data is never stored on our servers\n✓ You can revoke access at any time\n✓ All communications are encrypted (HTTPS/WSS)',
    'deriv.popupBlocked': 'Popup blocked. Allow popups to connect with the Broker.',
    'deriv.connectionSuccess': 'Broker account connected successfully!',
    'deriv.connectionError': 'Error connecting to Broker',
    'deriv.startConnectionError': 'Error starting connection to Broker',
    'deriv.disconnectionSuccess': 'Broker account disconnected successfully!',
    'deriv.disconnectionError': 'Error disconnecting from Broker',
    'deriv.afterSignup': 'After creating your account, come back here to connect!',
    
    // Courses
    'courses.title': 'Premium Trading Academy',
    'courses.loadingCourses': 'Loading courses...',
    'courses.previous': 'Previous',
    'courses.completed': 'Completed',
    'courses.markCompleted': 'Mark Completed',
    'courses.next': 'Next',
    'courses.classesCount': '{current} of {total} classes',
    'courses.selectClass': 'Select a Class',
    'courses.selectClassDescription': 'Choose a class from the library {location} to start your learning journey',
    'courses.locationBelow': 'below',
    'courses.locationBeside': 'beside',
    'courses.courseLibrary': 'Course Library',
    'courses.noCoursesAvailable': 'No courses available',
    'courses.classCompleted': 'Class marked as completed!',
    'courses.errorLoadingCourses': 'Error loading courses',
    
    // Profile
    'profile.title': 'My Profile',
    'profile.personalInfo': 'Personal Information',
    'profile.changePassword': 'Change Password',
    'profile.fullName': 'Full Name',
    'profile.emailCannotChange': 'Email cannot be changed',
    'profile.saveChanges': 'Save Changes',
    'profile.saving': 'Saving...',
    'profile.changing': 'Changing...',
    'profile.changePasswordButton': 'Change Password',
    'profile.memberSince': 'Member since',
    'profile.administrator': 'Administrator',
    'profile.client': 'Client',
    'profile.user': 'User',
    'profile.minCharacters': 'Minimum 6 characters',
    
    // Settings
    'settings.title': 'Settings',
    'settings.language': 'Language',
    'settings.selectLanguage': 'Select Language',
    'settings.accountInfo': 'Account Information',
    'settings.user': 'User',
    'settings.type': 'Type',
    
    // Languages
    'language.portuguese': 'Português (Brasil)',
    'language.english': 'English (US)',
    'language.spanish': 'Español',
    
    // Messages
    'message.profileUpdated': 'Profile updated successfully!',
    'message.passwordChanged': 'Password changed successfully!',
    'message.languageChanged': 'Language changed successfully!',
    'message.loginSuccess': 'Login successful!',
    'message.logoutSuccess': 'Logout successful!',
    'message.accountCreated': 'Account created successfully! You can now login.',
    
    // Errors
    'error.nameRequired': 'Name is required',
    'error.emailRequired': 'Email is required',
    'error.passwordRequired': 'Password is required',
    'error.currentPasswordRequired': 'Current password is required',
    'error.newPasswordRequired': 'New password is required',
    'error.passwordsNotMatch': 'Passwords do not match',
    'error.minPassword': 'Password must be at least 6 characters',
    'error.invalidEmail': 'Please enter a valid email',
    'error.emailInUse': 'Email is already in use',
    'error.invalidCredentials': 'Invalid credentials',
  },
  
  es: {
    // Navigation and Layout
    'nav.dashboard': 'Panel',
    'nav.bots': 'Bots',
    'nav.operations': 'Operaciones',
    'nav.bankManagement': 'Gestión Bancaria',
    'nav.courses': 'Cursos',
    'nav.connect': 'Conectar Bróker',
    'nav.users': 'Usuarios',
    'nav.theme': 'Tema',
    'nav.deriv': 'Config. Deriv',
    'nav.broker': 'Bróker',
    'nav.profile': 'Perfil',
    'nav.settings': 'Configuración',
    'nav.logout': 'Cerrar Sesión',
    
    // Common
    'common.save': 'Guardar',
    'common.cancel': 'Cancelar',
    'common.edit': 'Editar',
    'common.delete': 'Eliminar',
    'common.loading': 'Cargando...',
    'common.name': 'Nombre',
    'common.email': 'Email',
    'common.password': 'Contraseña',
    'common.confirmPassword': 'Confirmar Contraseña',
    'common.currentPassword': 'Contraseña Actual',
    'common.newPassword': 'Nueva Contraseña',
    
    // Dashboard
    'dashboard.welcome': 'Bienvenido',
    'dashboard.platform': 'Plataforma de Trading Inteligente Premium',
    'dashboard.connectBroker': 'Para comenzar a operar, necesitas conectar tu cuenta del Bróker.',
    'dashboard.alreadyAccount': '¿Ya tienes una cuenta? Conéctate. ¿No tienes una? Crea una nueva cuenta gratuita.',
    'dashboard.connectAccount': 'Conectar Cuenta del Bróker',
    'dashboard.createAccount': 'Crear Cuenta del Bróker',
    'dashboard.brokerAccount': 'Cuenta del Bróker',
    'dashboard.connected': 'Conectado',
    'dashboard.notConnected': 'Cuenta no conectada',
    'dashboard.connect': 'Conectar',
    'dashboard.operationStatus': 'Estado de la Operación',
    'dashboard.operating': 'Operando',
    'dashboard.stopped': 'Detenido',
    'dashboard.startOperation': 'Iniciar Operación',
    'dashboard.quickAccess': 'Acceso Rápido',
    'dashboard.botOperations': 'Operaciones con Bots',
    'dashboard.tradingCourses': 'Cursos de Trading',
    'dashboard.myProfile': 'Mi Perfil',
    'dashboard.riskWarning': 'Advertencia de Riesgo: El trading involucra riesgos significativos. Puedes perder parte o todo tu capital invertido. Nunca inviertas más de lo que puedes permitirte perder.',
    
    // Operations
    'operations.title': 'Panel de Operaciones Premium',
    'operations.connectNeeded': 'Para comenzar a operar, necesitas conectar tu cuenta del Bróker.',
    'operations.connectAccount': 'Conectar Cuenta del Bróker',
    'operations.selectBot': 'Seleccionar Bot',
    'operations.startOperation': 'Iniciar Operación',
    'operations.stopOperation': 'Detener Operación',
    'operations.operating': 'Operando...',
    'operations.configuration': 'Configuración',
    'operations.entryAmount': 'Monto de Entrada',
    'operations.martingale': 'Martingala',
    'operations.maxHands': 'Máximo de Manos',
    'operations.maxRed': 'Máximo de Rojos',
    'operations.stopLoss': 'Stop Loss',
    'operations.takeProfit': 'Take Profit',
    'operations.save': 'Guardar Configuración',
    'operations.cancel': 'Cancelar',
    'operations.availableBots': 'Bots Disponibles',
    'operations.noBots': 'No hay bots disponibles',
    'operations.available': 'Disponible',
    'operations.createdOn': 'Creado el',
    'operations.operationStatus': 'Estado de la Operación',
    'operations.connectToStart': 'Conecta tu cuenta del Bróker para comenzar',
    'operations.connectBroker': 'Conectar al Bróker',
    'operations.selectBotToStart': 'Selecciona un bot para comenzar',
    'operations.chooseBotFromList': 'Elige un bot de la lista del lado',
    'operations.status': 'Estado:',
    'operations.operationRunning': 'Operando',
    'operations.operationStopped': 'Detenido',
    'operations.operationLog': 'Registro de Operaciones',
    'operations.configureBot': 'Configurar {botName}',
    'operations.entryValue': 'Valor de Entrada ($)',
    'operations.martingaleValue': 'Valor de Martingala',
    'operations.maxHandsOptional': 'Máximo de Manos (opcional)',
    'operations.maxRedOptional': 'Máximo de Rojos (opcional)',
    'operations.stopLossOptional': 'Stop Loss (opcional)',
    'operations.takeProfitOptional': 'Take Profit (opcional)',
    
    // Bank Management
    'bank.title': 'Gestión Bancaria',
    'bank.refresh': 'Actualizar',
    'bank.configure': 'Configurar',
    'bank.initialCapital': 'Capital Inicial',
    'bank.positiveDays': 'Días Positivos',
    'bank.negativeDays': 'Días Negativos',
    'bank.hitRate': 'Tasa de Acierto',
    'bank.currentConfig': 'Configuración Actual',
    'bank.target': 'Meta',
    'bank.stopLoss': 'Stop Loss',
    'bank.capital': 'Capital',
    'bank.growthProjection': 'Proyección de Crecimiento (Mensual - 30 días)',
    'bank.day': 'Día',
    'bank.stopWin': 'Stop Win',
    'bank.deposit': 'Depósito',
    'bank.finalBalance': 'Saldo Final',
    'bank.result': 'Resultado',
    'bank.accumulated': 'Acumulado',
    'bank.operationRecords': 'Registros de Operaciones',
    'bank.newRecord': 'Nuevo Registro',
    'bank.noRecordsFound': 'No se encontraron registros',
    'bank.startAddingResults': 'Comienza agregando tu primer resultado de operación para seguir tu progreso',
    'bank.date': 'Fecha',
    'bank.status': 'Estado',
    'bank.actions': 'Acciones',
    'bank.edit': 'Editar',
    'bank.configTitle': 'Configuración de Gestión Bancaria',
    'bank.initialDeposit': 'Depósito Inicial ($)',
    'bank.initialBankValue': 'Valor inicial de tu banco',
    'bank.dailyTarget': 'Meta Diaria (%)',
    'bank.desiredDailyGain': 'Porcentaje de ganancia diaria deseada',
    'bank.maxDailyLoss': 'Porcentaje máximo de pérdida diaria',
    'bank.editRecord': 'Editar Registro',
    'bank.newOperationRecord': 'Nuevo Registro de Operación',
    'bank.operationDate': 'Fecha de Operación',
    'bank.positiveForGain': 'Valor positivo para ganancia, negativo para pérdida',
    'bank.objectiveAchieved': 'Objetivo Alcanzado',
    'bank.pending': 'Pendiente',
    'bank.targetReached': 'Meta Alcanzada',
    'bank.observations': 'Observaciones',
    'bank.addObservations': 'Agrega tus observaciones sobre la operación...',
    'bank.update': 'Actualizar',
    'bank.configSavedSuccess': '¡Configuración guardada exitosamente!',
    'bank.fillRequiredFields': 'Llena los campos obligatorios',
    'bank.recordUpdatedSuccess': '¡Registro actualizado exitosamente!',
    'bank.recordAddedSuccess': '¡Registro agregado exitosamente!',
    
    // Deriv Connection
    'deriv.title': 'Integración del Bróker',
    'deriv.subtitle': 'Conecta tu cuenta del Bróker para comenzar a usar bots de trading automatizados',
    'deriv.connectionStatus': 'Estado de Conexión',
    'deriv.connected': 'Conectado',
    'deriv.notConnected': 'No conectado',
    'deriv.accountConnectedSuccess': '¡Cuenta conectada exitosamente!',
    'deriv.account': 'Cuenta',
    'deriv.connectFirst': 'Para usar los bots de trading, conecta tu cuenta del Bróker primero.',
    'deriv.disconnecting': 'Desconectando...',
    'deriv.disconnectFromBroker': 'Desconectar del Bróker',
    'deriv.connecting': 'Conectando...',
    'deriv.connectWithBroker': 'Conectar con el Bróker',
    'deriv.noAccountYet': '¿Aún no tienes cuenta? Crear Cuenta del Bróker',
    'deriv.whyConnect': '¿Por qué conectar?',
    'deriv.automatedTrading': 'Trading Automatizado',
    'deriv.automatedTradingDesc': 'Ejecuta estrategias 24/7 sin intervención manual',
    'deriv.secureConnection': 'Conexión Segura',
    'deriv.secureConnectionDesc': 'OAuth2 oficial del Bróker, tus datos están protegidos',
    'deriv.multipleAccounts': 'Múltiples Cuentas',
    'deriv.multipleAccountsDesc': 'Gestiona cuentas demo y reales simultáneamente',
    'deriv.securityPrivacy': 'Seguridad y Privacidad',
    'deriv.securityPoints': '✓ La conexión utiliza OAuth2 oficial del Bróker\n✓ Tus datos de inicio de sesión nunca se almacenan en nuestros servidores\n✓ Puedes revocar el acceso en cualquier momento\n✓ Todas las comunicaciones están encriptadas (HTTPS/WSS)',
    'deriv.popupBlocked': 'Popup bloqueado. Permite popups para conectar con el Bróker.',
    'deriv.connectionSuccess': '¡Cuenta del Bróker conectada exitosamente!',
    'deriv.connectionError': 'Error al conectar con el Bróker',
    'deriv.startConnectionError': 'Error al iniciar conexión con el Bróker',
    'deriv.disconnectionSuccess': '¡Cuenta del Bróker desconectada exitosamente!',
    'deriv.disconnectionError': 'Error al desconectar del Bróker',
    'deriv.afterSignup': '¡Después de crear tu cuenta, vuelve aquí para conectar!',
    
    // Courses
    'courses.title': 'Academia de Trading Premium',
    'courses.loadingCourses': 'Cargando cursos...',
    'courses.previous': 'Anterior',
    'courses.completed': 'Completada',
    'courses.markCompleted': 'Marcar Completada',
    'courses.next': 'Siguiente',
    'courses.classesCount': '{current} de {total} clases',
    'courses.selectClass': 'Seleccionar una Clase',
    'courses.selectClassDescription': 'Elige una clase de la biblioteca {location} para comenzar tu viaje de aprendizaje',
    'courses.locationBelow': 'abajo',
    'courses.locationBeside': 'al lado',
    'courses.courseLibrary': 'Biblioteca de Cursos',
    'courses.noCoursesAvailable': 'No hay cursos disponibles',
    'courses.classCompleted': '¡Clase marcada como completada!',
    'courses.errorLoadingCourses': 'Error al cargar cursos',
    
    // Profile
    'profile.title': 'Mi Perfil',
    'profile.personalInfo': 'Información Personal',
    'profile.changePassword': 'Cambiar Contraseña',
    'profile.fullName': 'Nombre Completo',
    'profile.emailCannotChange': 'El email no se puede cambiar',
    'profile.saveChanges': 'Guardar Cambios',
    'profile.saving': 'Guardando...',
    'profile.changing': 'Cambiando...',
    'profile.changePasswordButton': 'Cambiar Contraseña',
    'profile.memberSince': 'Miembro desde',
    'profile.administrator': 'Administrador',
    'profile.client': 'Cliente',
    'profile.user': 'Usuario',
    'profile.minCharacters': 'Mínimo 6 caracteres',
    
    // Settings
    'settings.title': 'Configuración',
    'settings.language': 'Idioma',
    'settings.selectLanguage': 'Seleccionar Idioma',
    'settings.accountInfo': 'Información de la Cuenta',
    'settings.user': 'Usuario',
    'settings.type': 'Tipo',
    
    // Languages
    'language.portuguese': 'Português (Brasil)',
    'language.english': 'English (US)',
    'language.spanish': 'Español',
    
    // Messages
    'message.profileUpdated': '¡Perfil actualizado exitosamente!',
    'message.passwordChanged': '¡Contraseña cambiada exitosamente!',
    'message.languageChanged': '¡Idioma cambiado exitosamente!',
    'message.loginSuccess': '¡Inicio de sesión exitoso!',
    'message.logoutSuccess': '¡Cierre de sesión exitoso!',
    'message.accountCreated': '¡Cuenta creada exitosamente! Ahora puedes iniciar sesión.',
    
    // Errors
    'error.nameRequired': 'El nombre es obligatorio',
    'error.emailRequired': 'El email es obligatorio',
    'error.passwordRequired': 'La contraseña es obligatoria',
    'error.currentPasswordRequired': 'La contraseña actual es obligatoria',
    'error.newPasswordRequired': 'La nueva contraseña es obligatoria',
    'error.passwordsNotMatch': 'Las contraseñas no coinciden',
    'error.minPassword': 'La contraseña debe tener al menos 6 caracteres',
    'error.invalidEmail': 'Por favor ingresa un email válido',
    'error.emailInUse': 'El email ya está en uso',
    'error.invalidCredentials': 'Credenciales inválidas',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage deve ser usado dentro de um LanguageProvider');
  }
  return context;
};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>('pt');

  useEffect(() => {
    const savedLanguage = localStorage.getItem('language') as Language;
    if (savedLanguage && ['pt', 'en', 'es'].includes(savedLanguage)) {
      setLanguageState(savedLanguage);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string): string => {
    return (translations[language] as Record<string, string>)[key] || key;
  };

  const value: LanguageContextType = {
    language,
    setLanguage,
    t,
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};